CREATE TABLE CUSTOMER_INFO
(
	CUST_ID           NUMBER(18) NOT NULL,
	CUST_NO           VARCHAR2(35 CHAR) NOT NULL,
	CUST_LAST_NAME    VARCHAR2(35 CHAR) NOT NULL,
	CUST_FIRST_NAME   VARCHAR2(35 CHAR) NOT NULL,
	CUST_PHONE        NUMBER(18) NOT NULL,
	CUST_ADDR_LINE1   VARCHAR2(250 CHAR) NOT NULL,
	CUST_ADDR_LINE2   VARCHAR2(250 CHAR),
	CUST_CITY         VARCHAR2(50 CHAR) NOT NULL,
	CUST_STATE        VARCHAR2(50 CHAR) NOT NULL,
    CUST_POSTAL_CODE  VARCHAR2(20 CHAR) NOT NULL,
	CUST_COUNTRY      VARCHAR2(10 CHAR) NOT NULL
)
/
CREATE TABLE ACCOUNT_INFO(
	ACCOUNT_ID         NUMBER(18) NOT NULL,
	ACCOUNT_NO         VARCHAR2(35 CHAR) NOT NULL,
	ACCOUNT_TYPE       VARCHAR2(35 CHAR) NOT NULL,
    FK_ACCOUNT_CUST_ID NUMBER(18) NOT NULL)
/
ALTER TABLE CUSTOMER_INFO ADD CONSTRAINT PK_CUST_ID PRIMARY KEY (CUST_ID)
/
ALTER TABLE ACCOUNT_INFO ADD CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY (ACCOUNT_ID)
/
ALTER TABLE ACCOUNT_INFO ADD CONSTRAINT FK_ACCOUNT_INFO_CUST_ID FOREIGN KEY (FK_ACCOUNT_CUST_ID) REFERENCES CUSTOMER_INFO (CUST_ID)
/
