CREATE TABLE CUSTOMER_INFO
(
	CUST_ID           NUMBER(18) NOT NULL,
	CUST_NO           VARCHAR2(35 CHAR) NOT NULL,
	CUST_LAST_NAME    VARCHAR2(35 CHAR) NOT NULL,
	CUST_FIRST_NAME   VARCHAR2(35 CHAR) NOT NULL,
	CUST_PHONE        NUMBER(18) NOT NULL,
	CUST_ADDR_LINE1   VARCHAR2(250 CHAR) NOT NULL,
	CUST_ADDR_LINE2   VARCHAR2(250 CHAR),
	CUST_CITY         VARCHAR2(50 CHAR) NOT NULL,
	CUST_STATE        VARCHAR2(50 CHAR) NOT NULL,
    CUST_POSTAL_CODE  VARCHAR2(20 CHAR) NOT NULL,
	CUST_COUNTRY      VARCHAR2(10 CHAR) NOT NULL
)
/
CREATE TABLE ACCOUNT_INFO(
	ACCOUNT_ID         NUMBER(18) NOT NULL,
	ACCOUNT_NO         VARCHAR2(35 CHAR) NOT NULL,
	ACCOUNT_TYPE       VARCHAR2(35 CHAR) NOT NULL,
    FK_ACCOUNT_CUST_ID NUMBER(18) NOT NULL)
/
ALTER TABLE CUSTOMER_INFO ADD CONSTRAINT PK_CUST_ID PRIMARY KEY (CUST_ID)
/
ALTER TABLE ACCOUNT_INFO ADD CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY (ACCOUNT_ID)
/
ALTER TABLE ACCOUNT_INFO ADD CONSTRAINT FK_ACCOUNT_INFO_CUST_ID FOREIGN KEY (FK_ACCOUNT_CUST_ID) REFERENCES CUSTOMER_INFO (CUST_ID)
/
INSERT INTO CUSTOMER_INFO (CUST_ID, CUST_NO, CUST_LAST_NAME, CUST_FIRST_NAME, CUST_PHONE, CUST_ADDR_LINE1,CUST_ADDR_LINE2,CUST_CITY,CUST_STATE,CUST_POSTAL_CODE,CUST_COUNTRY)
  VALUES (1001, 290185382643, 'PASPULA', 'JAGANMOHAN', 9535719989, 'SRINIVASNAGR','BSK 1 STAGE','BNG','KA','560050','IN')
/
INSERT INTO CUSTOMER_INFO (CUST_ID, CUST_NO, CUST_LAST_NAME, CUST_FIRST_NAME, CUST_PHONE, CUST_ADDR_LINE1,CUST_ADDR_LINE2,CUST_CITY,CUST_STATE,CUST_POSTAL_CODE,CUST_COUNTRY)
  VALUES (1002, 280195832634, 'PASPULA', 'ABHUDAY JAGANATH', 9000122309, 'SRINIVASNAGR','BSK 2 STAGE','BNG','KA','560050','IN')
/
INSERT INTO ACCOUNT_INFO (ACCOUNT_ID, ACCOUNT_NO, ACCOUNT_TYPE,FK_ACCOUNT_CUST_ID) VALUES (2001, 237795852607, 'SAVINGS',1001)
/
INSERT INTO ACCOUNT_INFO (ACCOUNT_ID, ACCOUNT_NO, ACCOUNT_TYPE,FK_ACCOUNT_CUST_ID) VALUES (2002, 347895862709, 'LOAN',1001)
/
INSERT INTO ACCOUNT_INFO (ACCOUNT_ID, ACCOUNT_NO, ACCOUNT_TYPE,FK_ACCOUNT_CUST_ID) VALUES (2003, 245895854602, 'SAVINGS',1002)
/
INSERT INTO ACCOUNT_INFO (ACCOUNT_ID, ACCOUNT_NO, ACCOUNT_TYPE,FK_ACCOUNT_CUST_ID) VALUES (2004, 147894882708, 'LOAN',1002)
/
